const A = require('./DA.json')
const B = require('./DB.json')
const C = require('./DC.json')
const D = require('./DD.json')
const E = require('./DE.json')
const F = require('./DF.json')
const G = require('./DG.json')
const H = require('./DH.json')
const I = require('./DI.json')
const J = require('./DJ.json')
const K = require('./DK.json')
const L = require('./DL.json')
const M = require('./DM.json')
const N = require('./DN.json')
const O = require('./DO.json')
const P = require('./DP.json')
const Q = require('./DQ.json')
const R = require('./DR.json')
const S = require('./DS.json')
const T = require('./DT.json')
const U = require('./DU.json')
const V = require('./DV.json')
const W = require('./DW.json')
const X = require('./DX.json')
const Y = require('./DY.json')
const Z = require('./DZ.json')

export const vocab = e => {
    console.log(e)
}